#!/bin/bash
# find vagrant machines and get userinput
result=$(vagrant global-status | grep "libvirt" | awk 'function basename(file) {sub(".*/", "", file); return file;} function status(stat) { if (stat == "running") {return "🔵"} else {return "🔴"}} {print status($4)," ", $2":"basename($5), "(" $1 ")"}' | rofi -dmenu -p "" | awk '{print $1, $3}' | sed 's/[)(]//g')

id=$(echo $result | awk '{print $2}')
status=$(echo $result | awk '{print $1}')

echo $status

if [[ $id == "" ]]; then
  exit 1
fi
if [[ $status == "🔵" ]]; then
  mate-terminal -e "bash -c 'vagrant ssh $id; exec bash\'"
else
  notify-send "Vagrant" "Starting machine $id..."
  vagrant up $id && notify-send "Vagrant" "Machine $id is up."
fi
